### ISSUE TITLE
Cups is not recognised as a unit

### ISSUE THREAD

**Issue by mintsoft** [elohmrow/Convert-Pluggable#1]
Heya,

Related to: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1767

It looks like the alias doesn't exist for `cup` : https://github.com/elohmrow/Convert-Pluggable/blob/master/lib/Convert/Pluggable.pm#L1114

**Comment by elohmrow** [comment]
@mintsoft can this wait to go in with the bigger changes i had worked on? if not, i can push a small release tomorrow.

**Comment by mintsoft** [comment]
@elohmrow it's certainly not urgent!

**Comment by elohmrow** [comment]
@mintsoft - i think this one is ok to close, since the alias is there now, and the real issue is in 1767 (above).  i have added 1767 to the TODO in the latest v of C::P on CPAN
